<?php
/**
 * Hooks for importer
 *
 * @package MrBara
 */


/**
 * Importer the demo content
 *
 * @since  1.0
 *
 */
function mrbara_importer() {
	return array(
		array(
			'name'       => 'Home Book 2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-book/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-book/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-book/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-book/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-book/2/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Book 2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary'      => 'primary-menu',
				'mobile'       => 'mobile-menu',
				'footer'       => 'footer-menu',
				'product_cats' => 'product-categories',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 875,
					'height' => 875,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home MarketPlace 3',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/3/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-markets/3/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/3/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Market 3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary'      => 'primary-menu',
				'mobile'       => 'mobile-menu',
				'footer'       => 'footer-menu',
				'product_cats' => 'product-categories',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 875,
					'height' => 875,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home MarketPlace',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-markets/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/1/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Market 1',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary'      => 'primary-menu',
				'mobile'       => 'mobile-menu',
				'footer'       => 'footer-menu',
				'product_cats' => 'product-categories',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 875,
					'height' => 875,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home MarketPlace V2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-markets/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-markets/2/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Market 2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary'      => 'primary-menu',
				'mobile'       => 'mobile-menu',
				'footer'       => 'footer-menu',
				'product_cats' => 'product-categories',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 875,
					'height' => 875,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Book',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-book/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-book/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-book/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-book/widgets.wie',
			'pages'      => array(
				'front_page' => 'Home Book',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary'      => 'primary-menu',
				'mobile'       => 'mobile-menu',
				'footer'       => 'footer-menu',
				'product_cats' => 'product-categories',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 875,
					'height' => 875,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Full Width',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/full-width/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-fashion/full-width/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/full-width/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Full Width',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 645,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home SideBar',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/sidebar/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-fashion/sidebar/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/sidebar/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home SideBar',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 645,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home LookBook',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/lookbook/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-fashion/lookbook/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/lookbook/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home LookBook',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 645,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Full Slider',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/full-slider/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-fashion/full-slider/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/full-slider/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Full Slider',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 645,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Carousel',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/carousel/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-fashion/carousel/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/widgets.wie',
			'pages'      => array(
				'front_page' => 'Home Carousel',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 645,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Parallax',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/parallax/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-fashion/parallax/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/parallax/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Parallax',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 645,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Split Slider',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/split-slider/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-fashion/split-slider/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion/widgets.wie',
			'pages'      => array(
				'front_page' => 'Home Split',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 645,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Fashion App',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion-app/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion-app/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-fashion-app/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion-app/widgets.wie',
			'pages'      => array(
				'front_page' => 'Home Fashion App',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
		),
		array(
			'name'       => 'Home Fashion Studio',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion-studio/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion-studio/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-fashion-studio/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion-studio/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-fashion-studio/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Fashion Studio',
				'blog'       => 'Blog',
			),
			'menus'      => array(
				'primary'   => 'primary-menu',
				'mobile'    => 'mobile-menu',
				'footer'    => 'footer-menu',
				'secondary' => 'secondary-menu',
			),
		),
		array(
			'name'       => 'Home Single Product',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-single-product/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-single-product/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-single-product/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-single-product/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-single-product/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Single Product',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 645,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Boxed',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-boxed/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-boxed/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-boxed/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-boxed/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-boxed/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Boxed',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 640,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Bags 1',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-bag/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-bag/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-bag/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-bag/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-bag/1/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Bags',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Bags 2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-bag/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-bag/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-bag/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-bag/widgets.wie',
			'pages'      => array(
				'front_page' => 'Home Bag v2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Bags 3',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-bag/3/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-bag/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-bag/3/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-bag/widgets.wie',
			'pages'      => array(
				'front_page' => 'Home Bag v3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Shoes 1',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-shoes/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/1/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Shoes',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Shoes 2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-shoes/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/widgets.wie',
			'pages'      => array(
				'front_page' => 'Home Shoes v2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Shoes 3',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/3/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-shoes/3/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-shoes/3/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Shoes v3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Cosmetic 1',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/1/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Cosmetic',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Cosmetic 2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/2/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Cosmetic 2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Cosmetic 3',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/3/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/3/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-cosmetic/3/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Cosmetic v3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Tech 1',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-tech/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/1/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Tech',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 875,
					'height' => 875,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Tech 2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-tech/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/2/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Tech v2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 875,
					'height' => 875,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Tech 3',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/3/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-tech/3/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/3/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Tech v3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 875,
					'height' => 875,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Tech 4',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/4/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-tech/4/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-tech/4/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Tech v4',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary'      => 'primary-menu',
				'mobile'       => 'mobile-menu',
				'footer'       => 'footer-menu',
				'product_cats' => 'product-categories',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 875,
					'height' => 875,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Barbershop',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-barbershop/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-barbershop/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-barbershop/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-barbershop/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-barbershop/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Barbershop',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 640,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 480,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Sunglass 1',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/1/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Sunglass',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 500,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Sunglass 2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/2/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Sunglass v2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 500,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Sunglass 3',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/3/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/3/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-sunglass/3/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Sunglass v3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 500,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Watch 1',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-watch/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/1/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Watch',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 895,
					'height' => 895,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Watch 2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-watch/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/2/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Watch v2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 895,
					'height' => 895,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Watch 3',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/3/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-watch/3/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-watch/3/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Watch v3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 895,
					'height' => 895,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Sport 1',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-sport/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/1/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Sport',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 500,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 80,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Sport 2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-sport/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/2/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Sport v2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 500,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 80,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Sport 3',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/3/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-sport/3/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-sport/3/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Sport 3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 500,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 80,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Furniture 1',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-furniture/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/1/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Furniture',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 500,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 80,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Furniture 2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-furniture/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/2/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Furniture 2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 500,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 80,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Furniture 3',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/3/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-furniture/3/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/widgets.wie',
			'pages'      => array(
				'front_page' => 'Home Furniture 3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 500,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 80,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Furniture 4',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/4/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-furniture/4/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-furniture/4/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Furniture 4',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 480,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 500,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 80,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Jewelry 1',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/1/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/1/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/1/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Jewelry',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 640,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Jewelry 2',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/2/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/2/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/widgets.wie',
			'pages'      => array(
				'front_page' => 'Home Jewelry 2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 640,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
		array(
			'name'       => 'Home Jewelry 3',
			'preview'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/3/preview.jpg',
			'content'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/demo-content.xml',
			'customizer' => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/3/customizer.dat',
			'widgets'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/widgets.wie',
			'sliders'    => 'http://drfuri.com/soo-importer/mrbara/home-jewelry/3/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home Jewelry v3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
			'menus'      => array(
				'primary' => 'primary-menu',
				'mobile'  => 'mobile-menu',
				'footer'  => 'footer-menu',
			),
			'options'    => array(
				'shop_catalog_image_size'   => array(
					'width'  => 480,
					'height' => 640,
					'crop'   => 1,
				),
				'shop_single_image_size'    => array(
					'width'  => 500,
					'height' => 635,
					'crop'   => 1,
				),
				'shop_thumbnail_image_size' => array(
					'width'  => 80,
					'height' => 105,
					'crop'   => 1,
				),
			),
		),
	);
}

add_filter( 'soo_demo_packages', 'mrbara_importer', 30 );